image_size: 256
num_channels: 128
num_res_blocks: 1
channel_mult: ""
learn_sigma: true
class_cond: false
use_checkpoint: false
attention_resolutions: 16
num_heads: 4
num_head_channels: 64
num_heads_upsample: -1
use_scale_shift_norm: true
dropout: 0
resblock_updown: true
use_new_attention_order: false
