name: Lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install yamllint
        run: pip install yamllint
      - name: Install ruff
        run: pip install ruff
      - name: Lint YAML files
        run: yamllint .
      - name: Lint Python files
        run: ruff check --output-format=github .
